Update Android.yml

diff --git a/.github/workflows/Android.yml b/.github/workflows/Android.yml
--- a/.github/workflows/Android.yml
+++ b/.github/workflows/Android.yml
@@ -1,4 +1,5 @@
 name: Release
+
 on:
   push:
     tags:
@@ -11,17 +12,32 @@ jobs:
     permissions:
       contents: write
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-java@v3
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Setup Java
+        uses: actions/setup-java@v3
         with:
           distribution: temurin
-          java-version: 17 # Đặt phiên bản Java là 17
-      - uses: gradle/gradle-build-action@v2
+          java-version: 17
+
+      - name: Build Release APK
+        uses: gradle/gradle-build-action@v2
         with:
           gradle-version: current
           arguments: assembleRelease
-      - run: mv app/build/outputs/apk/release/app-release-unsigned.apk LittleGooseOffice_$GITHUB_REF_NAME.apk
-      - uses: ncipollo/release-action@v1
+
+      - name: Move APK File
+        run: |
+          RELEASE_APK=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
+          if [ -z "$RELEASE_APK" ]; then
+            echo "Error: APK file not found!"
+            exit 1
+          fi
+          mv "$RELEASE_APK" "LittleGooseOffice_${GITHUB_REF_NAME}.apk"
+
+      - name: Upload Release Artifact
+        uses: ncipollo/release-action@v1
         with:
           artifacts: "*.apk"
           token: ${{ secrets.GINTOKEN }}
